# Async e Await

## O que Ã© Async e Await?

Async e Await Ã© uma forma de lidar com cÃ³digo assÃ­ncrono (promises) de uma maneira aparentemente sÃ­ncrona.

## Exemplo Simples

No exemplo a seguir, primeiro declaramos uma funÃ§Ã£o que retorna uma promise que resolve o valor de ðŸ¤¡ depois de 2 segundos. EntÃ£o nÃ³s declaramos uma funÃ§Ã£o assÃ­ncrona (`async`) e esperamos (`await`) a promise ser resolvida antes de imprimir a mensagem no console.

```javascript
function scaryClown() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve("ðŸ¤¡");
    }, 2000);
  });
}

async function msg() {
  const msg = await scaryClown();
  console.log("Mensagem:", msg);
}

msg(); // Mensagem: ðŸ¤¡ <-- depois de 2 segundos
```

> `await` Ã© um novo operador usado para esperar uma promise ser resolvida ou rejeitada. Ela sÃ³ pode ser usada dentro uma funÃ§Ã£o assÃ­ncrona (`async`).

O poder do async/await se mostra quando existem diversos passos para pegar uma informaÃ§Ã£o, como no exemplo abaixo:

```javascript
function who() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve("ðŸ¤¡");
    }, 200);
  });
}

function what() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve("espreita");
    }, 300);
  });
}

function where() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve("nas sombras");
    }, 500);
  });
}

async function msg() {
  const a = await who();
  const b = await what();
  const c = await where();

  console.log(`${a} ${b} ${c}`);
}

msg(); // ðŸ¤¡ espreita nas sombras <-- depois de 1 segundo
```

Uma coisa para se tomar cuidado com exemplo acima Ã© que cada passo Ã© feito de forma sequencial, cada passo esperando o anterior para acontecer. Se pudermos, podemos fazer com que as funÃ§Ãµes executem em paralelo, ganhando em velocidade, para isso utilizamos o `Promise.all()`:

```javascript
async function msg() {
  const [a, b, c] = await Promise.all([who(), what(), where()]);

  console.log(`${a} ${b} ${c}`);
}

msg(); // ðŸ¤¡  espreita nas sombras <-- depois de 500ms
```

## Retornando Promises

FunÃ§Ãµes assÃ­ncronas sempre retornam uma promise, entÃ£o cÃ³digos como o seguinte podem nÃ£o ter o resultado esperado:

```javascript
async function hello() {
  return "Hello World!";
}

const b = hello();

console.log(b); // [object Promise] { ... }
```

Como uma promise Ã© retornada, podemos utilizar o `.then()` e o `.catch()`:

```javascript
async function hello() {
  return "Hello World!";
}

const b = hello();

b.then(x => console.log(x)); // Hello World!
```

## Tratando erros

Conseguimos tratar erros em funÃ§Ãµes assÃ­ncronas utilizando o `try...catch`.

```javascript
function yayOrNay() {
  return new Promise((resolve, reject) => {
    const val = Math.round(Math.random() * 1); // 0 ou 1, aleatÃ³riamente

    val ? resolve("Sortudo!!") : reject("Azarado ðŸ˜ ");
  });
}

async function msg() {
  try {
    const msg = await yayOrNay();
    console.log(msg);
  } catch (err) {
    console.log(err);
  }
}

msg(); // Sortudo!!
msg(); // Sortudo!!
msg(); // Sortudo!!
msg(); // Azarado ðŸ˜ 
msg(); // Sortudo!!
msg(); // Azarado ðŸ˜ 
msg(); // Azarado ðŸ˜ 
msg(); // Azarado ðŸ˜ 
msg(); // Azarado ðŸ˜ 
msg(); // Sortudo!!
```

Como funÃ§Ãµes assÃ­ncronas sempre retornam uma promise, podemos lidar com erros como normalmente fariamos, utilizando o `.catch()`.

```javascript
async function msg() {
  const msg = await yayOrNay();
  console.log(msg);
}

msg().catch(x => console.log(x));
```
